FROM ubuntu:latest

# Install OpenJDK and SSH server
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk openssh-server && \
    mkdir /var/run/sshd

RUN ssh-keygen -A && \
    chmod 600 /etc/ssh/ssh_host_* 
    # && \
    # chown root:root /etc/ssh/ssh_host_*

# Configure SSH server for non-root login
RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config 
# && \
#     sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Create a new user with a home directory
RUN useradd -ms /bin/bash jenkins && echo "jenkins:jenkins" | chpasswd

# Grant the new user sudo privileges (optional, if needed)
RUN apt-get install -y sudo && \
    usermod -aG sudo jenkins

RUN mkdir -p /home/jenkins/.ssh && \
    chmod 700 /home/jenkins/.ssh && \
    touch /home/jenkins/.ssh/authorized_keys && \
    chown -R jenkins:jenkins /home/jenkins/.ssh

# Grant Jenkins user sudo privileges without a password prompt
# RUN echo 'jenkins ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN echo "jenkins  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/jenkins

# Expose SSH 
EXPOSE 22

# Start SSHD and Nginx
CMD ["/usr/sbin/sshd", "-D"]
