---
# tasks file for config
- name: Gather facts
  setup:

- name: Check if the OS is Ubuntu
  debug:
    msg: "This machine is running Ubuntu"
  when: ansible_distribution == "Ubuntu"

- name: Check if the OS is Debian
  debug:
    msg: "This machine is running Debian"
  when: ansible_distribution == "Debian"

- name: Update apt repository
  apt:
    update_cache: yes
- name: Install required system packages
  apt:
    name:
      - net-tools
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg-agent
      - autoconf
      - dpkg-dev
      - file
      - g++
      - gcc
      - libc-dev
      - make
      - pkg-config
      - re2c
      - wget
    state: present
    update_cache: true
  become: true