---
# tasks file for app-deployment
- name: Update apt repository
  apt:
    update_cache: yes
- name: Install dependencies for Docker repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
- name: Install Docker Engine
  apt:
    name: docker-ce
    state: present
    update_cache: yes
- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true
- name: Verify Docker installation
  command: docker --version
  register: docker_version
  failed_when: docker_version.rc != 0
  changed_when: false
- name: Display Docker version
  debug:
    msg: "Docker version: {{ docker_version.stdout }}"
- name: Pull the latest Docker image
  community.docker.docker_image:
    name: "{{ docker_image }}"
    tag: "{{ build_number }}"
    state: present

- name: Deploy reading recommendations app
  kubernetes.core.k8s:
    kubeconfig: "/kubeconfig"   
    state: present
    definition: "{{ lookup('file', 'deployment.yaml') }}"

- name: Expose Service
  kubernetes.core.k8s:
    kubeconfig: "/kubeconfig"   
    state: present
    definition: "{{ lookup('file', 'service.yaml') }}"   

# - name: Stop existing Docker container
#   community.docker.docker_container:
#     name: reading-recommendations
#     state: stopped
#     force_kill: yes
#   ignore_errors: true

# - name: Remove old Docker container
#   community.docker.docker_container:
#     name: reading-recommendations
#     state: absent

# - name: Run the new Docker container
#   community.docker.docker_container:
#     name: reading-recommendations
#     image: "{{ docker_image }}:{{ build_number }}"
#     state: started
#     ports:
#       - "{{ app_port }}:3000"
#     restart_policy: always
#     env:
#       NODE_ENV: production
