---
# tasks file for app-deployment
- name: Pull the latest Docker image
  ansible.builtin.shell: "docker pull {{docker_image}}:{{build_number}}"
  register: pull_result

- name: Debug the output of docker pull
  ansible.builtin.debug:
    var: pull_result.stdout

- name: Install Docker SDK for Python using apt
  apt:
    name: python3-docker
    state: present

