apiVersion: apps/v1
kind: Deployment
metadata:
  name: reading-recommendations-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reading-recommendations-app
  template:
    metadata:
      labels:
        app: reading-recommendations-app
    spec:
      containers:
      - name: reading-recommendations-app
        image: reading-recommendations:latest
        ports:
        - containerPort: 3000