---
# tasks file for docker
# - name: Download Docker Installation Script
#   ansible.builtin.shell: "curl -fsSL https://get.docker.com -o get-docker.sh"
#   args:
#     creates: get-docker.sh

# - name: Run Docker Installation Script
#   ansible.builtin.shell: "sh get-docker.sh"
#   args:
#     creates: /usr/bin/docker || /usr/local/bin/docker
#   register: docker_install_output
#   ignore_errors: true

# - name: Debug Docker installation output
#   debug:
#     var: docker_install_output.stderr

# - name: Start and Enable Docker Service
#   service:
#     name: docker
#     enabled: yes
#     state: started
#   become: true

# - name: Add the current user to the docker group
#   ansible.builtin.user:
#     name: "jenkins"  # Use the appropriate username
#     groups: docker
#     append: yes

# - name: Check Docker installation
#   ansible.builtin.command: docker --version
#   register: docker_version_check
#   failed_when: "'Docker version' not in docker_version_check.stdout"

# - name: Debug Docker version
#   debug:
#     var: docker_version_check.stdout

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Remove any existing Docker installation
  apt:
    name: docker-ce
    state: absent
  ignore_errors: true  # In case Docker is not installed, this will not cause an error

- name: Remove old versions of Docker if installed
  apt:
    name: docker
    state: absent
  ignore_errors: true  # To remove any leftover Docker packages

- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Download Docker’s official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker_gpg.key

- name: Add Docker’s GPG key
  apt_key:
    file: /tmp/docker_gpg.key
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
