---
# tasks file for docker
# - name: Download Docker Installation Script
#   ansible.builtin.shell: "curl -fsSL https://get.docker.com -o get-docker.sh"
#   args:
#     creates: get-docker.sh
# - name: Run Docker Installation Script
#   ansible.builtin.shell: "sh get-docker.sh"
#   args:
#     creates: /usr/bin/docker || /usr/local/bin/docker
#   register: docker_install_output
#   ignore_errors: true

# - name: Debug Docker installation output
#   debug:
#     var: docker_install_output.stderr

# - name: Start and Enable Docker Service
#   service:
#     name: docker
#     enabled: yes
#     state: started
# - name: Add the current user to the docker group
#   ansible.builtin.user:
#     name: "jenkins"  # Use the appropriate username
#     groups: docker
#     append: yes

# - name: Check Docker installation
#   ansible.builtin.command: docker --version
#   register: docker_version_check
#   failed_when: "'Docker version' not in docker_version_check.stdout"

# - name: Debug Docker version
#   debug:
#     var: docker_version_check.stdout
# - name: Remove old Docker versions
#   apt:
#     name:
#       - docker
#       - docker-engine
#       - docker.io
#       - containerd
#       - runc
#     state: absent
#     purge: yes

# - name: Remove Docker-related leftover files
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - /var/lib/docker
#     - /etc/docker
#     - /var/lib/containerd
#     - /run/docker
#     - /run/containerd
    
# - name: Install Docker from Ubuntu repositories
#   apt:
#     name: docker.io
#     state: present
#   become: true

# - name: Ensure Docker service is enabled and running
#   service:
#     name: docker
#     state: started
#     enabled: true
#   become: true

# - name: Add user to Docker group
#   user:
#     name: "{{ ansible_user }}"
#     groups: docker
#     append: true
#   become: true

- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common

- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Print architecture variables
  ansible.builtin.debug:
    msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present

- name: Install Docker and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service