---
# tasks file for docker
- name: Install Python requests library via apt
  apt:
    name: python3-requests
    state: present
  become: true
- name: Download Docker Installation Script
  ansible.builtin.shell: "curl -fsSL https://get.docker.com -o get-docker.sh"
  args:
    creates: get-docker.sh
- name: Run Docker Installation Script
  ansible.builtin.shell: "sh get-docker.sh"
  args:
    creates: /usr/bin/docker
- name: Start Docker Service
  service:
    name: docker
    enabled: yes
    state: started
- name: Add the current user to the docker group
  ansible.builtin.user:
    name: "jenkins"  # Use the current user running the playbook
    groups: docker
    append: yes